# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: prometheus
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  version: 1
  editable: true